apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster-03
  region: us-east-1     
availabilityZones:
  - us-east-1a
  - us-east-1b  
  
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: keda-operator
      namespace: keda
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonPrometheusQueryAccess"
managedNodeGroups:
- name: default-ng
  minSize: 1
  maxSize: 3
  desiredCapacity: 2
  labels: {role: mngworker}
  iam:
    withAddonPolicies:
      certManager: true
      cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
