apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  postgresql_conn_str: cG9zdGdyZXNxbDovL3Bvc3RncmVzOk5lbHNvbnJhajI2QHBvc3RncmVzLmNsZWd6M2h4d2Z1ZC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20vcG9zdGdyZXNz
  